### ISSUE TITLE
Fail to compile due to incorect permission on /src/leveldb

### ISSUE THREAD

**Issue by hackmyl1fe** [carsenk/denarius#1]
I think you are aware of this issue(and i know you are working on the AMD miner today) but
If you ever encounter the error
/src/leveldb/libleveldb.a: No such file or directory
/src/leveldb/libmemenv.a: No such file or directory
when compiling do the following:

cd leveldb
chmod 755 *
cd ..
and compile again

**Comment by carsenk** [comment]
Yea the compiled lib .a files are not included in the source, The leveldb should be chmodded now though with the last update and also cleaned up, So you will want to cd into the src/leveldb and do:

make

**Comment by hackmyl1fe** [comment]
Thanks!
