### ISSUE TITLE
Backup Wallet issue on Mac QT

### ISSUE THREAD

**Issue by radar24** [carsenk/denarius#105]
On Mac OS 10.12.6 with v2.0.5.0

when I click Backup Wallet menu on settings, window opens to select the directory for saving backup.
That windows constantly disappears right after it shows up. So I can't do backup wallet.

**Comment by carsenk** [comment]
We will investigate this issue, may not be fixed until a later release as it is a OS specific issue. For now, grab your wallet.dat manually and copy it somewhere else by grabbing it from your user Library in ``` /Library/Application Support/Denarius/ ```

**Comment by enkayz** [comment]
please test this issue with the latest v2.5 release
