### ISSUE TITLE
Changing layout

### ISSUE THREAD

**Issue by ThorthChariot** [carsenk/denarius#110]
Hey :) 

I've got a problem with layout of wallet. 

I have a little problem when i click this right bar

![Imagine](http://i61.photobucket.com/albums/h57/Thorth/u_close_zpsbjozm22k.jpg)
the options apper like this
![Imagine2](http://i61.photobucket.com/albums/h57/Thorth/u_open_zpsp1yn8yuc.jpg)

but is put to close when your not with cursor on that ...  and I have to click it again,  :'( and be very carrefull with my mouse :)

**Comment by carsenk** [comment]
Yes that is normal functionality of the wallet, if you don't like having to use that menu, then simply expand the wallet by resizing it or hitting maximize.
