### ISSUE TITLE
Attach block chain to download 

### ISSUE THREAD

**Issue by knkrth** [carsenk/denarius#138]
Hi, Can you upload the block chain up to the current block? It takes more than two days to fully sync on the new wallet.

**Comment by carsenk** [comment]
It is available from: https://gitlab.com/denarius/chaindata/blob/master/chaindata.zip

Direct Download Link: https://gitlab.com/denarius/chaindata/raw/master/chaindata.zip

Guide: https://denariustalk.org/index.php?/topic/157-sync-denarius-fast-any-os-chaindatazip/
