### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by knkrth** [carsenk/denarius#139]
Hi, Can you tell me how did you come with this value on `116   | 0x80000074 | DNR    | [Denarius](https://denarius.io)`  for BIP44?

**Comment by carsenk** [comment]
It is our BIP44 Cointype of the Derivation Path of Denarius, you can utilize the BIP39 Tool to generate a seed phrase or see how it works: https://iancoleman.io/bip39/

**Comment by knkrth** [comment]
Thank you, But how did you come up with this number `116` on,
```
{
            name: "DNR - Denarius",
            segwitAvailable: false,
            onSelect: function() {
               network = bitcoinjs.bitcoin.networks.denarius;
               setHdCoin(0);
           }
```
You set `0` But you entered `116` on BIP44 & What is this value `0x80000074 `?

**Comment by knkrth** [comment]
I find out how you get `116` from https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Coin_type But I don't know What's this hex value `0x80000074`?

**Comment by knkrth** [comment]
Oh ok, Thank you.
