### ISSUE TITLE
Error showing balance

### ISSUE THREAD

**Issue by ThorthChariot** [carsenk/denarius#141]
On v 2.5.2  on TAB Staking, the balance is freeze, isn't auto update or something

**Comment by carsenk** [comment]
The Staking Tab is for estimations only, it only provides estimates on inputs that you currently own in your wallet. You should not rely on the staking tab for stakes, as it is only estimations.

**Comment by ThorthChariot** [comment]
i know is estimations.... what i meen the balance for address isn't updated, also doesn't show all the address from 1 wallet...

**Comment by ThorthChariot** [comment]
ok :)
