### ISSUE TITLE
Wrong release version for Windows

### ISSUE THREAD

**Issue by esejuli94** [carsenk/denarius#144]
Hi, I downloaded the latest version from your releases (v2.5.2.0) for windows and when I opened it and I checked the version it said v2.5.0.0.

**Comment by carsenk** [comment]
Sorry about the mistake, it should now be v2.5.2 - The MD5 Hash for Denarius-v2.5.20-Win64.zip should match **6A55ED7FD519460A1971F123EA6C4E31**
