### ISSUE TITLE
Documented md5sum of latest macOS release is wrong

### ISSUE THREAD

**Issue by marsmensch** [carsenk/denarius#148]
Documented on the release page:
> - Denarius-v3.0-Win64.zip MD5 Checksum: C24C6BB10279B9620797967BC12B5C8A
> - Denarius-v3.0-macOS.dmg MD5 Checksum: 7022E027592A7B2BB5620E668445755B
> - denariusd-v3-ubuntu1604.tar.gz MD5 Checksum: 62263D4CB560A3C8CA279ACFED4B62DB

Actual results:
```
$ md5 Denarius-v3.0-Win64.zip
MD5 (Denarius-v3.0-Win64.zip) = c24c6bb10279b9620797967bc12b5c8a
$ md5 Denarius-v3.0-macOS.dmg
MD5 (Denarius-v3.0-macOS.dmg) = 47da5c35d1a7a9eb7c9380ce4b0d25c4
$ md5 denariusd-v3-ubuntu1604.tar.gz
MD5 (denariusd-v3-ubuntu1604.tar.gz) = 62263d4cb560a3c8ca279acfed4b62db
```

**Comment by carsenk** [comment]
I will verify this and get it updated. Thanks

**Comment by carsenk** [comment]
Updated.
