### ISSUE TITLE
Issue with sendtoaddress command

### ISSUE THREAD

**Issue by esejuli94** [carsenk/denarius#149]
Hi, I'm trying to send an certain amount to an address with a comment longer than 24 characters. 

So, for example, when I use this command:
`sendtoaddress <denariusaddress> <amount> [comment] [comment-to] [narration]`

with this data:
`sendtoaddress <address...> 1 <string_longer_than_24_chars> "" ""`

I get this message:

> Narration must be 24 characters or less. (code -1)

I think it is combining these two commands:

`sendtoaddress <denariusaddress> <amount> [comment] [comment-to] [narration]`
`endtoaddress <denariusaddress> <amount> [narration]`

**Comment by carsenk** [comment]
DNR transactions can contain a narration up to 24 characters long, as well as a comment for the transaction. They are both separate options, you can try out PoD in the QT wallet as well to visually see how it utilizes narrations and comments. This is normal functionality, so this issue will be closed.
