### ISSUE TITLE
Cannot compile under Ubuntu 16, tor makes problem

### ISSUE THREAD

**Issue by djspacedevil** [carsenk/denarius#153]
Hy, i cannot compile with the new "tor" client inside.

```
make -f makefile.unix USE_UPNP=
cc -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wno-format -Wno-unused-parameter -Wno-literal-suffix -g -DBOOST_SPIRIT_THREADSAFE -I/bin/tribus/Denarius/denarius/src -I/bin/tribus/Denarius/denarius/src/obj -I/bin/tribus/Denarius/denarius/src/tor -I/bin/tribus/Denarius/denarius/src/json -DIS_ARCH_64 -I/bin/tribus/Denarius/denarius/src/leveldb/include -DUSE_LEVELDB -I/bin/tribus/Denarius/denarius/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/address.d -o obj/address.o tor/address.c
cc1: warning: command line option '-Wno-literal-suffix' is valid for C++/ObjC++ but not for C [enabled by default]
tor/address.c: In function 'tor_addr_parse_PTR_name':
tor/address.c:522:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < 16; ++i) {
     ^
tor/address.c:522:5: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [obj/address.o] Error 1
```

so i add -std=gnu99 to the makefile.unix under obj/%.o: tor/%.c and obj/anonymize.o: tor/anonymize.cpp after -c $(xCXXFLAGS) to check if it works... but wont. 

Then i become this error:
```
obj/crypto.o: In function `crypto_strongest_rand_syscall':
/bin/tribus/Denarius/denarius/src/tor/crypto.c:2864: undefined reference to `getentropy'
collect2: error: ld returned 1 exit status
make: *** [denariusd] Error 1
```
How can i fix it, or remove tor, when i only want a server wallet for mining?

**Comment by carsenk** [comment]
You shouldn't need to add -std=gnu99 to the daemon compiling set, -std=gnu99 may only be needed for the QT if you are having issues with its current QMAKE Flag while compiling on Linux, which is within your denarius-qt.pro file. 

For this issue with the makefile.unix try running:
`make CXXFLAGS="-D_DEFAULT_SOURCE=1" -f makefile.unix
`
Or/and setting `#define HAVE_GETENTROPY` in src/tor/orconfig_linux.h to 0 from 1 may help.

**Comment by ste26054** [comment]
Hi,

I am getting a similar error on a raspberry pi3, with both options provided, on `v3.1` / `master` too (I had successfully compiled `v2.5.2.0` on it):

Here are some details:

```
pi@raspberrypi3:~/denarius/src $ make CXXFLAGS="-D_DEFAULT_SOURCE=1" -f makefile.unix
cc -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wno-format -Wno-unused-parameter -Wno-literal-suffix -g -DBOOST_SPIRIT_THREADSAFE -I/home/pi/denarius/src -I/home/pi/denarius/src/obj -I/home/pi/denarius/src/tor -I/home/pi/denarius/src/json -DIS_ARCH_64 -DUSE_UPNP=1 -I/home/pi/denarius/src/leveldb/include -DUSE_LEVELDB -I/home/pi/denarius/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2 -D_DEFAULT_SOURCE=1 -MMD -MF obj/address.d -o obj/address.o tor/address.c
cc1: warning: command line option ‘-Wno-literal-suffix’ is valid for C++/ObjC++ but not for C
tor/address.c: In function ‘tor_addr_parse_PTR_name’:
tor/address.c:522:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int i = 0; i < 16; ++i) {
     ^
tor/address.c:522:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
makefile.unix:369: recipe for target 'obj/address.o' failed
make: *** [obj/address.o] Error 1
```

Thanks!

**Comment by carsenk** [comment]
I am unable to replicate these compile issues on my end, Ubuntu 16.04 compiles fine with all the required deps just fine. If you are trying to compile the QT on Ubuntu you may need to change the line in the denarius-qt.pro, the QMAKE Flag from stdlib=c99 to gnu99

Otherwise just download the Ubuntu16.04 binary :) https://github.com/carsenk/denarius/releases/download/v3.1/denariusd-v3.1-ubuntu1604.tar.gz

**Comment by djspacedevil** [comment]
I fixed for my self with:

```
git clone https://github.com/carsenk/denarius
cd denarius/src/leveldb/
make libleveldb.a libmemenv.a && cd ..
```
now open file  src/tor/orconfig_linux.h and go to line 142 and set 
```#define HAVE_GETENTROPY 0```

open file src/tor/crypto.c and go to line 2864 and replace the return with:
```(void) out;```

Now you can start the make with:
```make CXXFLAGS="-std=gnu99" USE_UPNP= -f makefile.unix```
 
And my pool https://miner-control.de is back online with this coin ;)

If you want to spend some D,   -> DMTEybxc88axHjmit13FJCjTaphYBBPC1L
i have only 2.33 D ;(

**Comment by buzzkillb** [comment]
This is how I got ubuntu 16 QT compiled
```
sudo apt-get --assume-yes install git unzip build-essential libssl-dev libdb++-dev libboost-all-dev libqrencode-dev libminiupnpc-dev libgmp-dev libevent-dev autogen automake  libtool libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools
sudo apt-get --assume-yes install qt5-default
sed -i 's/c99/gnu99/' ~/denarius/denarius-qt.pro
qmake "USE_QRCODE=1" "USE_UPNP=1" denarius-qt.pro
make
```

**Comment by carsenk** [comment]
(NOTE: This issue was fixed in a few releases back) but just to follow up on this and close it out:

There is now a new flag added in the makefile.unix and denarius-qt.pro files in the latest v3.3.8.1 release of D to help with compiling denariusd and Denarius QT for all sorts of OSs to compile without Tor support, you would want to add "USE_NATIVETOR=-" to compile without -nativetor= support:

Example: `qmake "USE_NATIVETOR=-" denarius-qt.pro` or `make -f "USE_NATIVETOR=-" makefile.unix `

https://github.com/carsenk/denarius/commit/a7ea311e08e499eebf7aaf51829a7db02bcca181
