### ISSUE TITLE
Mn payment hardfork issue, chain diverged !!!

### ISSUE THREAD

**Issue by 216k155** [carsenk/denarius#167]
Hi there,
I found the following issues:

In some places, float point arithmetics is used to calculate important for consensus values. U never want to do so because float point arithmetics isn't deterministic. Examples of such places: "payRate = ((double)(payValue / COIN) / MASTERNODE_FAIR_PAYMENT_ROUNDS)*100;" in masternode.cpp, "int maxrank = mnCount * 0.2;" in main.cpp.
Rank calculation has height-based cache. I see it there "if (masternodePayments.vecMasternodeRanksLastUpdated == pindexBest->nHeight) return true;" in masternode.cpp. After a reorg., new block will have the same block. height, but different hash. Cache must refer to block hash, not block height.

**Comment by carsenk** [comment]
@enkayz Attempted a fix using your insight with the PR that was merged into master recently: https://github.com/carsenk/denarius/pull/168

**Comment by carsenk** [comment]
This is now fixed for now, changes may still be made, but we do have a stable chain now running on the latest master branch from PR https://github.com/carsenk/denarius/pull/169
