### ISSUE TITLE
FortunaStake enabled needs an icon

### ISSUE THREAD

**Issue by buzzkillb** [carsenk/denarius#182]
Example of QT wallet with an icon when fsconflock=1 is active, or maybe when the wallet sees 1 line in the fortunastake.conf file.
![04-wallet-reset](https://user-images.githubusercontent.com/18255964/50049984-0aa99300-00a5-11e9-9eef-6bdf4fd49769.png)

**Comment by carsenk** [comment]
Consider it done in the next release!
