### ISSUE TITLE
Staking not working with RPC

### ISSUE THREAD

**Issue by esejuli94** [carsenk/denarius#184]
Hello,

I try to enable staking with walletpassphrase command but it doesn't work. It worked good before the last big update.

The command output is fine but stake is never activated. The command I'm using is something like this one:

`
walletpassphrase XXXX YYYYYYYY true
`

Thanks in advance.

**Comment by carsenk** [comment]
Try staking with v3.3.4 we made some improvements and bug fixes. You can git pull our v3.4 branch before we officially release it.

**Comment by esejuli94** [comment]
Okay, I'm going to try

**Comment by esejuli94** [comment]
It worked! Thanks 👍
