### ISSUE TITLE
Fortuna Stake tab doesnt always Refresh

### ISSUE THREAD

**Issue by buzzkillb** [carsenk/denarius#194]
If a fortunastake server goes down, the main QT **_My Denarius Fortuna Stakes_** Status doesn't change from **_Active for payment_** to **_offline_**.

**Comment by manosv** [comment]
What is the progress with this issue ?

**Comment by carsenk** [comment]
We will more than likely remove this feature from the QT, to only display the current Fortuna Stake network, the interface is clunky and just causes problems with performance in general.

**Comment by carsenk** [comment]
This was fixed in: https://github.com/carsenk/denarius/commit/c1e550b34751184a4e03c9db15e27a449b63a9c3
