### ISSUE TITLE
daemon listtransactions issue

### ISSUE THREAD

**Issue by manosv** [carsenk/denarius#199]
when you do 
denariusd listtransactions 
with latest v3.3.7 but also exists as far back as v3.3(as far i remember)
all POS rewards as a masternode at least show as 0.00000000
the rewards are credited correctly in balance though

**Comment by carsenk** [comment]
Fixed in https://github.com/carsenk/denarius/commit/727f499a830520905a520dffcd4f4e663bda0ce4
