### ISSUE TITLE
daemon fortunastake status

### ISSUE THREAD

**Issue by manosv** [carsenk/denarius#200]
daemon v3.3.7(but this bug exists way far back)
When your wallet is locked and you do
denariusd fortunastake status
it doesnt show the true collateral address but this one
DMbDViy1z4gweDFaYCyayvnPFUERB5Hymk
which is not mine
e.g in my wallet with 4 FSs it shows

{
    "local" : {
        "status" : "unconfigured"
    },
    "scaleway7" : {
        "alias" : "fs1",
        "ipaddr" : "xxx.xxx.xxx.xxx:9999",
        "collateral" : "DMbDViy1z4gweDFaYCyayvnPFUERB5Hymk",
        "status" : "online",
        "lastpaidblock" : x,
        "version" : 33500
    },
    "scaleway9" : {
        "alias" : "scaleway9",
        "ipaddr" : "xxx.xxx.xxx.xxx:9999",
        "collateral" : "DMbDViy1z4gweDFaYCyayvnPFUERB5Hymk",
        "status" : "online",
        "lastpaidblock" : x,
        "version" : 33500
    },
    "scaleway6" : {
        "alias" : "scaleway6",
        "ipaddr" : "xxx.xxx.xxx.xxx:9999",
        "collateral" : "DMbDViy1z4gweDFaYCyayvnPFUERB5Hymk",
        "status" : "online",
        "lastpaidblock" : x,
        "version" : 33500
    },
    "scaleway8" : {
        "alias" : "scaleway8",
        "ipaddr" : "xxx.xxx.xxx.xxx:9999",
        "collateral" : "DMbDViy1z4gweDFaYCyayvnPFUERB5Hymk",
        "status" : "online",
        "lastpaidblock" : x,
        "version" : 33500
    }
}
if i unlock the wallet everything is fine showing my true Addresses.This has to be fixed because inexperienced users trying to create a FS are baffled by this, aand some lost 5000D trying to create a FS because of this.
My suggestion is to show the true collateral address even if the wallet is locked.If this is not technically possible then in place of the address put a msg telling the user to unlock the wallet.

**Comment by carsenk** [comment]
Fixed this issue in https://github.com/carsenk/denarius/commit/727f499a830520905a520dffcd4f4e663bda0ce4
