### ISSUE TITLE
Watched addresses

### ISSUE THREAD

**Issue by manosv** [carsenk/denarius#203]
V3.3.8.2 latest but also previous versions

The wallet is falsely trying to stake watched addresses(which clearly doesnt have the private keys of) and failing.I can see a lot of failed staking in the transactions list from watched addresses . Also the green icon for staking in bottom right is reporting way bigger weight than this wallet really has.

**Comment by manosv** [comment]
After contacting Carsen this problem is resolved with the latest commits

**Comment by carsenk** [comment]
Resolved in commit: https://github.com/carsenk/denarius/commit/456666088c74a46f9a48560ed40975c02386ebe5
