### ISSUE TITLE
Inability to Stake The Collateral if its older than 25days

### ISSUE THREAD

**Issue by manosv** [carsenk/denarius#205]
As the tittle suggests you cant stake the collateral if its older than 25days
I have tried everything.I shut off the vpss, the FSs are not on the list,i waited for a day staking
but still nothing.
There seems no problem staking the collateral if its newer than 20
it stakes immediately without having to wait for the FSs to go out of the list which suggests there is definitely a bug.The bug exists a long time now since 3.3 at least.I though i was doing something wrong but after talking to other members of the community they are having the same problem.Please fix

**Comment by buzzkillb** [comment]
Same issue with not being able to stake the 5000 D FortunaStake collateral sometimes. I kept thinking this is a weight against network weight thing, but maybe its a time thing?

Maybe some others could try leaving 5k in a FS for 21 days, then delete that single line in fortunastake.conf and try staking that single 5k collateral.

**Comment by Darkensan** [comment]
Just stopped a 41d old node and got same issue. no stacking reward from the 5k collateral.
For the next 15 minutes after breaking the node i recived a transaction every 2 minutes with the supposed stacking reward, but all of those failed reporting as "?".
In few days can break more nodes, as soon as they mature 21-22 days.

**Comment by carsenk** [comment]
This is somewhat normal operation, but you must STOP your FS node, add mnconflock=0 and fortunastake=0 to your conf and then you must wait for it to drop off the list to actually start staking the funds. For @manosv issue, I will need to get with you further to see what is going on exactly.

If you are seeing ? (Generated/Not Accepted) you are staking, but someone else beat you to solving that particular block, just keep trying ;)

**Comment by Darkensan** [comment]
@carsenk in my example i was reporting that the stacking weight accumulated from the node during his 41 days life, is not paid once you break it.

**Comment by buzzkillb** [comment]
On my wallet when I took a few FS's off to stake, the rest of the wallet stopped staking. Only once I moved those 5k's that wouldn't stake to a new txid, would the wallet start staking again.

On more recent FS's that I setup they staked fine, maybe about a week or 2 old. So its either time or weight.

**Comment by Darkensan** [comment]
i can add that if you add the removed node back, the rest of the wallet start to stake again as it does moving the coins to a new txid

**Comment by manosv** [comment]
its time to close this.The issue is resolved
