### ISSUE TITLE
‘fClient’ was not declared in this scope

### ISSUE THREAD

**Issue by chelahmy** [carsenk/denarius#22]
Compiling denarius-qt v1.0.7.0 in Debian produced the following errors:

> src/txdb-bdb.cpp:36:13: error: ‘fClient’ was not declared in this scope
     assert(!fClient);

> src/txdb-bdb.cpp:226:49: error: ‘GetArgInt’ was not declared in this scope
     int nCheckLevel = GetArgInt("-checklevel", 1);

> src/txdb-bdb.cpp:404:24: error: ‘class CBlockIndex’ has no member named ‘hashProofOfStake’
             pindexNew->hashProofOfStake = diskindex.hashProofOfStake;

I had no problem compiling the earlier version 1.0.6.0.

**Comment by carsenk** [comment]
For v1.0.7.0 If you are compiling the QT you must add the flag USE_LEVELDB=1 to the qmake command, like the below. This is fixed in the future v1.0.8.0, it will compile in the future by default with the TXDB LevelDB.

`qmake "USE_LEVELDB=1" "USE_UPNP=1" "USE_QRCODE=1" denarius-qt.pro`
