### ISSUE TITLE
Super slow gettransaction RPC

### ISSUE THREAD

**Issue by pinpins** [carsenk/denarius#222]
Hello,

Since like 06.05.2019 gettransaction rpc call takes more than 30 secs, killing ability to use daemon properly.

Ubuntu 16.04

thanks
pinpin

**Comment by carsenk** [comment]
I will investigate it further, I don't believe any changes were made to gettransaction only listtransactions 

What version are you using?

**Comment by pinpins** [comment]
double checked my yiimp code, there are two rpc calls in subject function gettransaction and getblock.

so I still believe it is gettransaction, where yiimp update confirmation for found blocks. 

I am on version 3.3.7.0

**Comment by carsenk** [comment]
@pinpins Does this issue still exist with the latest release, v3.3.9.1?

**Comment by pinpins** [comment]
No, haven't experienced issue anymore
