### ISSUE TITLE
Android Qt Wallet

### ISSUE THREAD

**Issue by knkrth** [carsenk/denarius#23]
Hi, Do you know how to build a Android Qt wallet?

**Comment by carsenk** [comment]
Yes, it's not something I would recommend with DNRs current structure and no thin client, running a full QT on Android is possible but just not fesible once the blockchain is larger. Though the device could support it, I would rather continue working on a Coinomi styled wallet for Android/Java that will utilize a new denariusj Java library similar to Bitcoinj.

**Comment by knkrth** [comment]
Ok. Can you provide steps on building Qt wallet for android on Qt creator. I Use Mac, What system you use?

**Comment by carsenk** [comment]
You want to setup the Android NDK and SDK, along with Java JDK, then you would want to compile all dependencies for Android with your ARM toolchain from the NDK for QT like openssl, bdb, boost, etc. The .pro file would need modification as well for android{}to include the include/lib and make flags
