### ISSUE TITLE
I am getting error from this line

### ISSUE THREAD

**Issue by kalinux0** [carsenk/denarius#232]
src/tor/compat_libevent.h:10:10: fatal error: event2/event.h: No such file or directory
 #include <event2/event.h>
          ^~~~~~~~~~~~~~~~
When compiling
I followed this video's steps : https://asciinema.org/a/179356

**Comment by carsenk** [comment]
The Asciinema videos are somewhat outdated at this point, you are just missing one of the dependencies "libevent"

``` sudo apt-get install libevent-dev obfs4proxy ```

This isn't an actual issue, just a matter of ensuring you get the right dependencies installed. This dependency is listed in the documentation, you can also compile Denarius without any native Tor support rendering no need for libevent-dev with the compile flag "USE_NATIVETOR=-".
