### ISSUE TITLE
Ubuntu 19.10 Daemon won't Compile (Fix)

### ISSUE THREAD

**Issue by buzzkillb** [carsenk/denarius#256]
I added -l boost_chrono \ to src/makefile.unix here
```
   -l curl \
   -l boost_chrono \
   -l ssl \
```
and now this line will compile
`OPENSSL_INCLUDE_PATH=/usr/local/ssl/include OPENSSL_LIB_PATH=/usr/local/ssl/lib make -f makefile.unix`

**Comment by carsenk** [comment]
Fixed in latest branch
