### ISSUE TITLE
v3.3.9.7 - can't select custom data directory when Denarius installed via snap

### ISSUE THREAD

**Issue by Shekelme** [carsenk/denarius#279]
I just can't select custom data directory when Denarius installed via snap. My separate HDD which I would like to use for blockchain data does not appear under /media mounting point:

![image](https://user-images.githubusercontent.com/26449500/86356579-ad7d2e80-bc96-11ea-8b24-b22b7fbdac6b.png)

**Comment by carsenk** [comment]
I believe this could be a Snap related issue, were you able to replicate the issue with a compiled wallet? I will get an external drive connected and test this out, I believe you said this was on Ubuntu 19.10 as well?

**Comment by Shekelme** [comment]
Yes, 19.10. It looks that compiled wallet is not able to start now - it hangs at "verifying the database" while doing nothing at all. So I'm running D wallet on Windows for now.
Sure it looks like Snap issue, maybe some permissions or smth. I don't want to get into it. While I understand that this is a "Linux way", I just don't wont to. Sorry. )

**Comment by buzzkillb** [comment]
Can you try this? I got it working, but not sure if its another thing I did first, or if the datadir flag is all you need.
`denarius -datadir=/home/USERNAME/denariussnap`
That's just an example for the main home directory, curious if it works on /media/denarius or something like that.

For some reason I can't get that Welcome window to pop up, so need to try some more stuff on a clean VM to figure out a way to break out of that directory you are forced into.

Also I noticed the compiled wallet segfaults on 19.10 and newer now. Same segfault when I compiled in Archlinux.

**Comment by buzzkillb** [comment]
Install denarius like this.
`snap install --devmode denarius`
Devmode will let you access out of the snap sandbox, but will not autoupdate. Please backup your wallet.dat and try this a few times to see if it works. I couldn't select the directory, but could input the full USB drive into the line.
![welcome-usb-mount](https://user-images.githubusercontent.com/18255964/86447054-9e63a400-bcc9-11ea-8a78-dd2b1c2bad81.png)
