### ISSUE TITLE
Error sending Message

### ISSUE THREAD

**Issue by ThorthChariot** [carsenk/denarius#30]
Hi :) 
We find a bug.
We try to send some message from wallet, the wallet cannot retrive the public key of an address, and of course the message cannot be send

**Comment by ThorthChariot** [comment]
on discordapp, there are some pinned message, with prinscreen

**Comment by enkayz** [comment]
your client will need to see some transactions performed by the intended destination address before it can get the public key, try sending and receiving some currency with the destination address first and let us know how it goes.

**Comment by ThorthChariot** [comment]
ok thanks for info :)

**Comment by ThorthChariot** [comment]
nope, doesn't work... try again with some address with a lot of transaction.... and the same think :)  a print screen is pinned on discordapp

**Comment by ThorthChariot** [comment]
everything is ok :)

**Comment by enkayz** [comment]
to clarify, the sending client needs to see transactions which are sent by the destination address in the blockchain in order to get the public key

**Comment by ThorthChariot** [comment]
yeap i got the ideea, i finally succedd to send a message to some one :)  and receive my message, and that person try to send me a message, but i didn't receive anything

**Comment by inliquid** [comment]
The client provides 2 fields:
- Send To
- Public key
it should be enough to fill them in and send the message. The ability of having the address in blockchain can be used to obtain 'pub key' but should not stop anyone from sending the message. It makes no sense to ask user to make transactions BEFORE using 'messages' capability.

**Comment by inliquid** [comment]
Hi @ThorthChariot can you please reopen this bug? For me the problem was not solved.
