### ISSUE TITLE
some of the code is not python 3 code.

### ISSUE THREAD

**Issue by keefer223** [carsenk/denarius#305]
I'm trying to compile the program, but it errors out. To see if this would be an easy fix, I ran the source code thru pycharm. 

General errors - Syntax errors - 148
Python errors - Unresolved references - 65
                          the majority are attributed to print statements and code - acct = raw_input
Shell script - ShellCheck - 4
XML - XML highlighting errors - 441

I believe the following line from the source code is python2:  print "\n---An error occurred---\n"

I'd love to compile the source code but there are just too many issues to deal with without more documentation.

**Comment by carsenk** [comment]
You would not compile Denarius with Python, Denarius is built with C++/QT, you can check the compiling guides on https://denarius.wiki
