### ISSUE TITLE
Add Windows notifications

### ISSUE THREAD

**Issue by inliquid** [carsenk/denarius#45]
Please add a notification feature in Windows for events such as successful wallet backup, like is done in Litecoin, Dash, and others. It is very useful when getting feedback of whether or not it was successful and for self-check (such as the path for saving file and it's name).

**Comment by enkayz** [comment]
the notification feature already exists in windows and is more generally for transactions.

we can add more notification events, which events do you feel need notifications?

**Comment by inliquid** [comment]
As I told it would be very helpful to see when wallet backup is succeeded within the _notification message_ showing:
- Program name, action taken
- Result (success or not)
- Path and file name

Right now there is no feedback from the application at all. I have to open target dir in order to check that the wallet backup has been saved.

**Comment by enkayz** [comment]
we will consider adding this ability in a more general sense in a future release; notifications for wallet backups are one event which would become part of a larger notification system which would enable the user to disable notifications for several categories of events

issue will be left open for community input on which events are suitable for notification event triggering

**Comment by carsenk** [comment]
![](https://i.imgur.com/cOpBWLt.png)

This was resolved in https://github.com/carsenk/denarius/commit/dda87bce7fcda91cc1e0bbc4bb6e1fb2667cd749

Branch v3.4, will be merged into master soon.
