### ISSUE TITLE
Add warning when closing wallet

### ISSUE THREAD

**Issue by inliquid** [carsenk/denarius#46]
When you closing wallet in Windows, the wallet window disappears just at that moment. However some background process is still running. If you try to restart Denarius wallet after closing it will tell that it can't obtain file lock. In other crypto wallets including Bitcoin there is small window appearing which displays warning message that wallet is still closing and user have to wait for process to terminate.

**Comment by carsenk** [comment]
I will be looking into adding this in a future release.

**Comment by inliquid** [comment]
[Windows10] This is not solved, there is no warning that wallet is closing, so I have to monitor running processes or logs.

**Comment by enkayz** [comment]
#115 adds this functionality
