### ISSUE TITLE
Rejected PoS trasactions participate in staking

### ISSUE THREAD

**Issue by inliquid** [carsenk/denarius#47]
In case when there was block generated by wallet under PoS, but which has already been rejected by network (so the transaction is not in any block in blockchain), and wallet knows that it was not accepted (it's shown in transaction list as conflicting), this transaction appear in staking like if it was normal one. Wallet has to clean staking list from these transactions.

**Comment by carsenk** [comment]
This was fixed in a long ago release, closing it out!
