### ISSUE TITLE
Add x64 binaries to distribution

### ISSUE THREAD

**Issue by inliquid** [carsenk/denarius#50]
Please consider adding x64 Windows/Mac binaries like usually done in other mature projects. Since almost all PCs/smartphones now run on 64bit architectures having 32bit wallets may look odd.

**Comment by carsenk** [comment]
Added.

**Comment by inliquid** [comment]
I think 64bit installer is also needed.

**Comment by carsenk** [comment]
Yea, I want to make a newer installer in general that has a bit more options, so this will be done in the soon future.
