### ISSUE TITLE
[masternodes] Wallet still estimates wrong amounts

### ISSUE THREAD

**Issue by inliquid** [carsenk/denarius#76]
It's shame. I repeat here what I have reported many times already. 

![default](https://user-images.githubusercontent.com/6797881/36621770-db0a93f6-190a-11e8-838c-8dcf66df9f0f.png)

**Comment by carsenk** [comment]
For testnet issues, join our #testnet channel on our Discord, Issues here are only for mainnet. We are aware of the testnet and have been working on it 24/7, you are an outdated client as well now. Closing this issue.

**Comment by inliquid** [comment]
But I can't join, you banned me! :D

**Comment by inliquid** [comment]
Problem is still there.

**Comment by carsenk** [comment]
Yea this is a cosmetic issue, we are working more pressing issues currently. We will unban you, but please behave!

**Comment by carsenk** [comment]
This was now fixed as well, latest commit in masternodes branch: https://github.com/carsenk/denarius/commit/2f5caf48e6acee39a44cbe247a69d4097fb0fe35

Also just to note, block maturity is 20 blocks on testnet and 30 on mainnet.
