### ISSUE TITLE
Compile error in Ubuntu 16.04

### ISSUE THREAD

**Issue by sylph93** [carsenk/denarius#87]
I got error while I compiled v2.0.0.
I followed latest instruction and got message while 'make'.

In file included from src/qt/qcustomplot.cpp:26:0:
src/qt/qcustomplot.h:54:28: fatal error: QtPrintSupport: No such file or directory
compilation terminated.

**Comment by enkayz** [comment]
which version of Qt are you compiling against?

**Comment by sylph93** [comment]
I followed this instruction. 
https://denariustalk.org/index.php?/topic/138-guide-building-denarius-qtdenariusd-on-ubuntu/

**Comment by carsenk** [comment]
I tested on Ubuntu 16.04 and it builds with no errors with QT4, you just need to ensure you are building with QT4. QtPrintSupport is only supported on QT5+ and we do not support QT5 yet. What does the command below return for you?

`qmake -v`

**Comment by sylph93** [comment]
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

**Comment by carsenk** [comment]
You can install QT4 with 
`sudo apt-get install libqt4-dev`

You can switch QT versions with the variable QT_SELECT=qt4 or qmake -qt=qt4:
```
QT_SELECT=qt4 qmake --version
qmake -qt=qt4 --version
```

**Comment by sylph93** [comment]
I got an new error after toggle to QT4

build/ui_richlist.h:13:29: fatal error: QtWidgets/QAction: No such file or directory
compilation terminated.

**Comment by enkayz** [comment]
In QT5, please try with QT += widget printsupport in the denarius-qt.pro file

**Comment by sylph93** [comment]
It worked. I edited denarius-qt.pro file.
Add 'printsupport' next to 'QT += widget'

QT += widget 
to
QT += Widget printsupport

 Worked like charm.

Please add this to new release.
