### ISSUE TITLE
Wallet language can't be changed in settings

### ISSUE THREAD

**Issue by inliquid** [carsenk/denarius#93]
Wallet settings can't override system locale settings. If you open the settings, change language from default to some specific language, f.e. English (US), and restart the wallet, default (system-wide) language will remain.

**Comment by manosv** [comment]
This issue still exists in latest versions V3.3.8.x

**Comment by carsenk** [comment]
This option may be removed, so that all wallets are forced to use the system set language.  It would free up some repo space and compile size...it is a bit redundant

**Comment by manosv** [comment]
Please dont remove it.I like using the english language in programs instead of my native langueage.If it is removed the messages will be in english or my local?

**Comment by carsenk** [comment]
It should default to your system language, I will look into it

**Comment by carsenk** [comment]
Lets see what people think about just making it english and removing the language switching?

**Comment by Darkensan** [comment]
imho 
default=eng 
other languages="let them be the way they are" even if the result is an half working transaltion
fix the issue in a later moment when more time and if it become "essential"

**Comment by manosv** [comment]
I agree with Darkensan.Give people at least the choice.This is not Apple corp.
