### ISSUE TITLE
lock icon only says unlocked even if unlocked for staking 

### ISSUE THREAD

**Issue by zerosight** [carsenk/denarius#96]
When unlock for staking is done, the lock icon down bottom right is unlock image, and hover text is "wallet is encrypted and currently unlocked"    
should be Encrypted and unlocked for staking only

**Comment by carsenk** [comment]
On todo

**Comment by carsenk** [comment]
Fixed in https://github.com/carsenk/denarius/commit/b8203052a44785acf16ac128182bbb9c27c6127e (Way over due)
